USE QLGV;
GO

--Q35--
SELECT DISTINCT GV1.LUONG
FROM GIAOVIEN AS GV1
WHERE GV1.LUONG >= ALL(
	SELECT LUONG
	FROM GIAOVIEN AS GV2
)

--Q36--
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV
WHERE GV.LUONG >= ALL(
	SELECT DISTINCT LUONG
	FROM GIAOVIEN AS GV2
)

--Q37--
SELECT DISTINCT GV.LUONG
FROM GIAOVIEN AS GV
WHERE GV.LUONG >= ALL(
	SELECT DISTINCT LUONG
	FROM GIAOVIEN AS GV2
	WHERE GV2.MABM = 'HTTT'
) AND GV.MABM = 'HTTT'

--Q38--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE year(GV.NGSINH) <= ALL(
	SELECT DISTINCT year(GV2.NGSINH)
	FROM GIAOVIEN AS GV2
	WHERE GV2.MABM = 'HTTT'
) AND GV.MABM = 'HTTT'

--Q39--
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1
LEFT JOIN BOMON
ON GV1.MABM = BOMON.MABM
LEFT JOIN KHOA
ON BOMON.MAKHOA = KHOA.MAKHOA
WHERE year(GV1.NGSINH) >= ALL(
	SELECT DISTINCT year(GV2.NGSINH)
	FROM GIAOVIEN AS GV2
	LEFT JOIN BOMON
	ON GV2.MABM = BOMON.MABM
	LEFT JOIN KHOA
	ON BOMON.MAKHOA = KHOA.MAKHOA
	WHERE KHOA.TENKHOA = N'Công nghệ thông tin'
) AND KHOA.TENKHOA = N'Công nghệ thông tin'

--Q40--
SELECT DISTINCT GV.HOTEN, KHOA.TENKHOA
FROM GIAOVIEN AS GV
LEFT JOIN BOMON
ON GV.MABM = BOMON.MABM
LEFT JOIN KHOA
ON BOMON.MAKHOA = KHOA.MAKHOA
WHERE GV.LUONG >= ALL(
	SELECT DISTINCT GV1.LUONG
	FROM GIAOVIEN AS GV1
)

--Q41--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV
JOIN (
	SELECT MAX(GV1.LUONG) AS LUONG, GV1.MABM
	FROM GIAOVIEN AS GV1
	GROUP BY GV1.MABM
) AS GV1
ON GV.LUONG = GV1.LUONG
AND GV.MABM = GV1.MABM

--Q42--
SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1
WHERE DT1.TENDT NOT IN (
	SELECT DISTINCT DETAI.TENDT
	FROM DETAI
	RIGHT JOIN THAMGIADT
	ON DETAI.MADT = THAMGIADT.MADT
	LEFT JOIN GIAOVIEN
	ON THAMGIADT.MAGV = GIAOVIEN.MAGV
	WHERE GIAOVIEN.HOTEN = N'Nguyễn Hoài An'
)

--Q43--
SELECT DISTINCT DT1.TENDT, GV1.HOTEN AS GVCNDT
FROM DETAI AS DT1
LEFT JOIN GIAOVIEN AS GV1
ON DT1.GVCNDT = GV1.MAGV
WHERE DT1.TENDT NOT IN (
	SELECT DISTINCT DETAI.TENDT
	FROM DETAI
	RIGHT JOIN THAMGIADT
	ON DETAI.MADT = THAMGIADT.MADT
	LEFT JOIN GIAOVIEN
	ON THAMGIADT.MAGV = GIAOVIEN.MAGV
	WHERE GIAOVIEN.HOTEN = N'Nguyễn Hoài An'
)

--Q44--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV
LEFT JOIN BOMON
ON GV.MABM = BOMON.MABM
LEFT JOIN KHOA
ON BOMON.MAKHOA = KHOA.MAKHOA
WHERE GV.MAGV NOT IN (
	SELECT DISTINCT TG1.MAGV
	FROM THAMGIADT AS TG1
	LEFT JOIN GIAOVIEN AS GV1
	ON TG1.MAGV = GV1.MAGV
	LEFT JOIN BOMON
	ON GV1.MABM = BOMON.MABM
	LEFT JOIN KHOA
	ON BOMON.MAKHOA = KHOA.MAKHOA
	WHERE KHOA.TENKHOA = N'Công nghệ thông tin'
) AND KHOA.TENKHOA = N'Công nghệ thông tin'

--Q45--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE GV.MAGV NOT IN (
	SELECT DISTINCT TG1.MAGV
	FROM THAMGIADT AS TG1
	LEFT JOIN GIAOVIEN AS GV1
	ON TG1.MAGV = GV1.MAGV
)

--Q46--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE GV.LUONG > ALL (
	SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1
	WHERE GV1.HOTEN = N'Nguyễn Hoài An'
)

--Q47--
SELECT DISTINCT TG1.MAGV, GV1.HOTEN
FROM THAMGIADT AS TG1
JOIN BOMON
ON TG1.MAGV = BOMON.TRUONGBM
LEFT JOIN GIAOVIEN AS GV1
ON BOMON.TRUONGBM = GV1.MAGV

--Q48--
SELECT GV1.HOTEN
FROM GIAOVIEN AS GV1
WHERE GV1.HOTEN IN (
	SELECT GV2.HOTEN
	FROM GIAOVIEN AS GV2
	WHERE GV2.MAGV != GV1.MAGV
	AND GV2.HOTEN = GV1.HOTEN
	AND GV2.MABM = GV1.MABM
)

--Q49--
SELECT GV0.HOTEN
FROM GIAOVIEN AS GV0
WHERE GV0.LUONG > ALL (
	SELECT TOP 1 GV1.LUONG AS LUONG
	FROM GIAOVIEN AS GV1
	LEFT JOIN BOMON AS BM1
	ON GV1.MABM = BM1.MABM
	WHERE BM1.TENBM = N'Công nghệ phần mềm'
	ORDER BY LUONG ASC
)

--Q50--
SELECT GV0.HOTEN
FROM GIAOVIEN AS GV0
WHERE GV0.LUONG > ALL (
	SELECT GV1.LUONG AS LUONG
	FROM GIAOVIEN AS GV1
	LEFT JOIN BOMON AS BM1
	ON GV1.MABM = BM1.MABM
	WHERE BM1.TENBM = N'Hệ thống thông tin'
)

--Q51--
SELECT K0.TENKHOA
FROM KHOA AS K0
JOIN (
	SELECT TOP 1 COUNT(GV.MAGV) AS SLGV, K1.MAKHOA
	FROM GIAOVIEN AS GV
	LEFT JOIN BOMON
	ON GV.MABM = BOMON.MABM
	LEFT JOIN KHOA AS K1
	ON K1.MAKHOA = BOMON.MAKHOA
	GROUP BY K1.MAKHOA
	ORDER BY SLGV DESC
) AS T
ON K0.MAKHOA = T.MAKHOA

--Q52--
SELECT TOP 1 GV1.HOTEN, COUNT(DT1.MADT) AS SLDT
FROM GIAOVIEN AS GV1
RIGHT JOIN DETAI AS DT1
ON GV1.MAGV = DT1.GVCNDT
GROUP BY GV1.MAGV, GV1.HOTEN
ORDER BY SLDT DESC

--Q53--
SELECT BM.MABM
FROM BOMON AS BM
JOIN (
	SELECT TOP 1 BM1.MABM, COUNT(GV1.MAGV) AS SLGV
	FROM GIAOVIEN AS GV1
	RIGHT JOIN BOMON AS BM1
	ON GV1.MABM = BM1.MABM
	GROUP BY BM1.MABM
	ORDER BY SLGV DESC
) AS T
ON BM.MABM = T.MABM

--Q54--
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN AS GV
LEFT JOIN BOMON AS BM
ON GV.MABM = BM.MABM
WHERE GV.MAGV IN (
	SELECT TOP 1 GV1.MAGV
	FROM GIAOVIEN AS GV1
	RIGHT JOIN THAMGIADT AS TG1
	ON GV1.MAGV = TG1.MAGV
	GROUP BY GV1.MAGV, GV1.HOTEN, GV1.MABM
	ORDER BY COUNT (DISTINCT MADT) DESC
)

--Q55--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
LEFT JOIN BOMON AS BM
ON GV.MABM = BM.MABM
WHERE GV.MAGV IN (
	SELECT TOP 1 GV1.MAGV
	FROM GIAOVIEN AS GV1
	RIGHT JOIN THAMGIADT AS TG1
	ON GV1.MAGV = TG1.MAGV
	WHERE GV1.MABM = 'HTTT'
	GROUP BY GV1.MAGV, GV1.HOTEN, GV1.MABM
	ORDER BY COUNT (DISTINCT MADT) DESC
)

--Q56--
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN AS GV
LEFT JOIN BOMON AS BM
ON GV.MABM = BM.MABM
LEFT JOIN NGUOITHAN AS NT
ON GV.MAGV = NT.MAGV
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM
HAVING COUNT(*) = ALL (
	SELECT TOP 1 COUNT (*) AS SLNT
	FROM GIAOVIEN AS GV1
	LEFT JOIN NGUOITHAN AS NT1
	ON GV1.MAGV = NT1.MAGV
	GROUP BY GV1.MAGV
	ORDER BY SLNT DESC
)

--Q57--
SELECT TOP 1 GV1.HOTEN, COUNT(DT1.MADT) AS SLDT
FROM GIAOVIEN AS GV1
RIGHT JOIN DETAI AS DT1
ON GV1.MAGV = DT1.GVCNDT
RIGHT JOIN BOMON AS BM
ON GV1.MAGV = BM.TRUONGBM
GROUP BY GV1.MAGV, GV1.HOTEN
ORDER BY SLDT DESC

