USE QLGV
GO

--Q58--
SELECT GV1.HOTEN
FROM THAMGIADT AS TG1
LEFT JOIN DETAI
ON TG1.MADT = DETAI.MADT
LEFT JOIN GIAOVIEN AS GV1
ON TG1.MAGV = GV1.MAGV
WHERE NOT EXISTS(
	(SELECT CHUDE.MACD FROM CHUDE)
	EXCEPT
	(SELECT DT2.MACD
	FROM THAMGIADT AS TG2
	LEFT JOIN DETAI AS DT2
	ON TG2.MADT = DT2.MADT
	WHERE TG2.MAGV = TG1.MAGV)
)

--Q59--
SELECT DT1.TENDT
FROM THAMGIADT AS TG1
LEFT JOIN DETAI AS DT1
ON TG1.MADT = DT1.MADT
WHERE (TG1.MAGV IN (SELECT GV1.MAGV FROM GIAOVIEN AS GV1 WHERE GV1.MABM = 'HTTT'))
GROUP BY DT1.TENDT
HAVING COUNT (DISTINCT TG1.MAGV) = (SELECT COUNT(GV1.MAGV) FROM GIAOVIEN AS GV1 WHERE GV1.MABM = 'HTTT')

--Q60--
SELECT DT1.TENDT
FROM THAMGIADT AS TG1
LEFT JOIN DETAI AS DT1
ON TG1.MADT = DT1.MADT
WHERE (TG1.MAGV IN (
	SELECT GV1.MAGV
	FROM GIAOVIEN AS GV1
	LEFT JOIN BOMON AS BM1
	ON GV1.MABM = BM1.MABM
	WHERE BM1.TENBM = N'Hệ thống thông tin')
)
GROUP BY DT1.TENDT
HAVING COUNT (DISTINCT TG1.MAGV) = (
	SELECT COUNT(GV1.MAGV)
	FROM GIAOVIEN AS GV1
	LEFT JOIN BOMON AS BM1
	ON GV1.MABM = BM1.MABM
	WHERE BM1.TENBM = N'Hệ thống thông tin'
)

--Q61--
SELECT TG1.MAGV
FROM THAMGIADT AS TG1
WHERE TG1.MADT IN (
	SELECT DT1.MADT FROM DETAI AS DT1
	WHERE DT1.MACD = 'QLGD'
)
GROUP BY TG1.MAGV
HAVING COUNT (DISTINCT TG1.MADT) =
(SELECT COUNT (DISTINCT DT2.MADT)
FROM DETAI AS DT2
WHERE DT2.MACD = 'QLGD')

--Q62--
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1
JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
WHERE TG1.MADT IN (
	SELECT DISTINCT DT2.MADT
	FROM GIAOVIEN AS GV2
	JOIN THAMGIADT AS TG2
	ON TG2.MAGV = GV2.MAGV
	LEFT JOIN DETAI AS DT2
	ON DT2.MADT = TG2.MADT
	WHERE GV2.HOTEN = N'Trần Trà Hương'
) AND GV1.HOTEN != N'Trần Trà Hương'
GROUP BY TG1.MADT, GV1.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = 
(SELECT COUNT (DT2.MADT)
FROM GIAOVIEN AS GV2
JOIN THAMGIADT AS TG2
ON TG2.MAGV = GV2.MAGV
LEFT JOIN DETAI AS DT2
ON DT2.MADT = TG2.MADT
WHERE GV2.HOTEN = N'Trần Trà Hương'
)

--Q63--
SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1
RIGHT JOIN THAMGIADT AS TG1
ON DT1.MADT = TG1.MADT
WHERE TG1.MAGV IN (
	SELECT DISTINCT GV2.MAGV
	FROM GIAOVIEN AS GV2
	LEFT JOIN BOMON AS BM2
	ON GV2.MABM = BM2.MABM
	WHERE BM2.TENBM = N'Hoá hữu cơ'
)
GROUP BY DT1.TENDT
HAVING COUNT (DISTINCT TG1.MAGV) =
(SELECT COUNT (GV2.MAGV)
FROM GIAOVIEN AS GV2
LEFT JOIN BOMON AS BM2
ON GV2.MABM = BM2.MABM
WHERE BM2.TENBM = N'Hoá hữu cơ')

-- Do trong bảng dữ liệu của ta không có bộ môn Hoá hữu cơ, ta sẽ test bằng tên bộ môn là Mạng máy tính với các logic giống nhau--

SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1
RIGHT JOIN THAMGIADT AS TG1
ON DT1.MADT = TG1.MADT
WHERE TG1.MAGV IN (
	SELECT DISTINCT GV2.MAGV
	FROM GIAOVIEN AS GV2
	LEFT JOIN BOMON AS BM2
	ON GV2.MABM = BM2.MABM
	WHERE BM2.TENBM = N'Mạng máy tính'
)
GROUP BY DT1.TENDT
HAVING COUNT (DISTINCT TG1.MAGV) =
(SELECT COUNT (GV2.MAGV)
FROM GIAOVIEN AS GV2
LEFT JOIN BOMON AS BM2
ON GV2.MABM = BM2.MABM
WHERE BM2.TENBM = N'Mạng máy tính')

--Q64--
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1
JOIN THAMGIADT AS TG1
ON Gv1.MAGV = TG1.MAGV
WHERE TG1.STT IN (
	SELECT TG2.STT
	FROM THAMGIADT AS TG2
	WHERE TG2.MADT = '006'
) AND TG1.MADT = '006'
GROUP BY TG1.MADT, GV1.HOTEN
HAVING COUNT (DISTINCT TG1.STT) =
(SELECT COUNT (DISTINCT TG2.STT)
FROM THAMGIADT AS TG2
WHERE TG2.MADT = '006'
)

--Q65--
SELECT TG1.MAGV
FROM THAMGIADT AS TG1
WHERE TG1.MADT IN (
	SELECT DT2.MADT 
	FROM DETAI AS DT2
	LEFT JOIN CHUDE AS CD2
	ON DT2.MACD = CD2.MACD
	WHERE CD2.MACD = N'Ứng dụng công nghệ'
)
GROUP BY TG1.MAGV
HAVING COUNT (DISTINCT TG1.MADT) =
(SELECT COUNT (DISTINCT DT2.MADT)
FROM DETAI AS DT2
LEFT JOIN CHUDE AS CD2
ON DT2.MACD = CD2.MACD
WHERE CD2.MACD = N'Ứng dụng công nghệ'
)

--Q66--
SELECT GV1.HOTEN
FROM GIAOVIEN AS GV1
JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
WHERE TG1.MADT IN (
	SELECT DT2.MADT
	FROM GIAOVIEN AS GV2
	RIGHT JOIN DETAI AS DT2
	ON GV2.MAGV = DT2.GVCNDT
	WHERE GV2.HOTEN = N'Trần Trà Hương'
) AND GV1.HOTEN != N'Trần Trà Hương'
GROUP BY GV1.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = 
(SELECT COUNT (DT2.MADT)
FROM GIAOVIEN AS GV2
RIGHT JOIN DETAI AS DT2
ON GV2.MAGV = DT2.GVCNDT
WHERE GV2.HOTEN = N'Trần Trà Hương'
)

--Q67--
SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1
JOIN THAMGIADT AS TG1
ON TG1.MADT = DT1.MADT
WHERE TG1.MAGV IN (
	SELECT DISTINCT GV2.MAGV
	FROM GIAOVIEN AS GV2
	LEFT JOIN THAMGIADT AS TG2
	ON GV2.MAGV = TG2.MAGV
	LEFT JOIN BOMON AS BM2
	ON GV2.MABM = BM2.MABM
	LEFT JOIN KHOA AS K2
	ON BM2.MAKHOA = K2.MAKHOA
	WHERE K2.TENKHOA = N'Công nghệ thông tin'
)
GROUP BY DT1.TENDT
HAVING COUNT (DISTINCT TG1.MAGV) = 
(
	SELECT COUNT(DISTINCT GV2.MAGV)
	FROM GIAOVIEN AS GV2
	LEFT JOIN THAMGIADT AS TG2
	ON GV2.MAGV = TG2.MAGV
	LEFT JOIN BOMON AS BM2
	ON GV2.MABM = BM2.MABM
	LEFT JOIN KHOA AS K2
	ON BM2.MAKHOA = K2.MAKHOA
	WHERE K2.TENKHOA = N'Công nghệ thông tin'
)

--Q68--
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1
JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
LEFT JOIN DETAI AS DT1
ON TG1.MADT = DT1.MADT
WHERE TG1.STT IN (
	SELECT TG2.STT
	FROM THAMGIADT AS TG2
	LEFT JOIN DETAI AS DT2
	ON TG2.MADT = DT2.MADT
	WHERE DT2.TENDT = N'Nghiên cứu tế bào gốc'
) AND DT1.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY TG1.MADT, GV1.HOTEN
HAVING COUNT (DISTINCT TG1.STT) =
(
	SELECT COUNT (DISTINCT TG2.STT)
	FROM THAMGIADT AS TG2
	LEFT JOIN DETAI AS DT2
	ON TG2.MADT = DT2.MADT
	WHERE DT2.TENDT = N'Nghiên cứu tế bào gốc'
)

--Q69--
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1
RIGHT JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
LEFT JOIN DETAI AS DT1
ON TG1.MADT = DT1.MADT
WHERE TG1.MADT IN (
	SELECT DISTINCT DT2.MADT
	FROM DETAI AS DT2
	WHERE DT2.KINHPHI > 100
)
GROUP BY GV1.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = (
	SELECT COUNT (DT2.MADT)
	FROM DETAI AS DT2
	WHERE DT2.KINHPHI > 100
)

--Q70--
SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1
JOIN THAMGIADT AS TG1
ON TG1.MADT = DT1.MADT
WHERE TG1.MAGV IN (
	SELECT DISTINCT GV2.MAGV
	FROM GIAOVIEN AS GV2
	LEFT JOIN THAMGIADT AS TG2
	ON GV2.MAGV = TG2.MAGV
	LEFT JOIN BOMON AS BM2
	ON GV2.MABM = BM2.MABM
	LEFT JOIN KHOA AS K2
	ON BM2.MAKHOA = K2.MAKHOA
	WHERE K2.TENKHOA = N'Sinh học'
)
GROUP BY DT1.TENDT
HAVING COUNT (DISTINCT TG1.MAGV) = 
(
	SELECT COUNT(DISTINCT GV2.MAGV)
	FROM GIAOVIEN AS GV2
	LEFT JOIN THAMGIADT AS TG2
	ON GV2.MAGV = TG2.MAGV
	LEFT JOIN BOMON AS BM2
	ON GV2.MABM = BM2.MABM
	LEFT JOIN KHOA AS K2
	ON BM2.MAKHOA = K2.MAKHOA
	WHERE K2.TENKHOA = N'Sinh học'
)

--Q71--
SELECT DISTINCT GV1.MAGV, GV1.HOTEN, GV1.NGSINH
FROM GIAOVIEN AS GV1
JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
LEFT JOIN DETAI AS DT1
ON TG1.MADT = DT1.MADT
WHERE TG1.STT IN (
	SELECT TG2.STT
	FROM THAMGIADT AS TG2
	LEFT JOIN DETAI AS DT2
	ON TG2.MADT = DT2.MADT
	WHERE DT2.TENDT = N'Ứng dụng hoá học xanh'
) AND DT1.TENDT = N'Ứng dụng hoá học xanh'
GROUP BY TG1.MADT, GV1.MAGV, GV1.HOTEN, GV1.NGSINH
HAVING COUNT (DISTINCT TG1.STT) =
(
	SELECT COUNT (DISTINCT TG2.STT)
	FROM THAMGIADT AS TG2
	LEFT JOIN DETAI AS DT2
	ON TG2.MADT = DT2.MADT
	WHERE DT2.TENDT = N'Ứng dụng hoá học xanh'
)

--Q72--
SELECT DISTINCT TG1.MAGV, GV1.HOTEN, BM1.TENBM, GV2.HOTEN AS GVQLCM
FROM THAMGIADT AS TG1
LEFT JOIN GIAOVIEN AS GV1
ON TG1.MAGV = GV1.MAGV
LEFT JOIN GIAOVIEN AS GV2
ON GV1.GVQLCM = GV2.MAGV
LEFT JOIN BOMON AS BM1
ON GV1.MABM = BM1.MABM
WHERE TG1.MADT IN (
	SELECT DT2.MADT 
	FROM DETAI AS DT2
	LEFT JOIN CHUDE AS CD2
	ON DT2.MACD = CD2.MACD
	WHERE CD2.MACD = N'Nghiên cứu phát triển'
)
GROUP BY TG1.MAGV, GV1.HOTEN, BM1.TENBM, GV2.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) =
(SELECT COUNT (DISTINCT DT2.MADT)
FROM DETAI AS DT2
LEFT JOIN CHUDE AS CD2
ON DT2.MACD = CD2.MACD
WHERE CD2.MACD = N'Nghiên cứu phát triển'
)

--Q73--
SELECT DISTINCT GV1.HOTEN, GV1.NGSINH, K1.TENKHOA, GV2.HOTEN AS TRUONGKHOA
FROM GIAOVIEN AS GV1
RIGHT JOIN THAMGIADT AS TG1
ON TG1.MAGV = GV1.MAGV
LEFT JOIN BOMON AS BM1
ON GV1.MABM = BM1.MABM
LEFT JOIN KHOA AS K1
ON BM1.MAKHOA = K1.MAKHOA
LEFT JOIN GIAOVIEN AS GV2
ON K1.TRUONGKHOA = GV2.MAGV
WHERE TG1.MADT IN (
	SELECT DISTINCT TG2.MADT
	FROM GIAOVIEN AS GV2
	RIGHT JOIN THAMGIADT AS TG2
	ON GV2.MAGV = TG2.MAGV
	WHERE GV2.HOTEN = N'Nguyễn Hoài An'
) AND GV1.HOTEN != N'Nguyễn Hoài An'
GROUP BY GV1.HOTEN, GV1.NGSINH, K1.TENKHOA, GV2.HOTEN
HAVING  COUNT(DISTINCT TG1.MADT) = (
	SELECT COUNT(DISTINCT TG2.MADT)
	FROM GIAOVIEN AS GV2
	RIGHT JOIN THAMGIADT AS TG2
	ON GV2.MAGV = TG2.MAGV
	WHERE GV2.HOTEN = N'Nguyễn Hoài An'
)

--Q74--
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1
RIGHT JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
LEFT JOIN BOMON AS BM1
ON GV1.MABM = BM1.MABM
LEFT JOIN KHOA AS K1
ON BM1.MAKHOA = K1.MAKHOA
WHERE TG1.MADT = ANY (
	SELECT DISTINCT DT4.MADT
	FROM DETAI AS DT4
	RIGHT JOIN THAMGIADT AS TG4
	ON DT4.MADT = TG4.MADT
	WHERE DT4.GVCNDT = ANY (
		SELECT GV4.MAGV
		FROM BOMON AS BM3
		LEFT JOIN KHOA AS K3
		ON BM3.MAKHOA = K3.MAKHOA
		RIGHT JOIN GIAOVIEN AS GV3
		ON GV3.MABM = BM3.MABM
		LEFT JOIN GIAOVIEN AS GV4
		ON BM3.TRUONGBM = GV4.MAGV
		WHERE K3.TENKHOA = N'Công nghệ thông tin'
		GROUP BY BM3.MABM, GV4.MAGV
		HAVING COUNT(GV3.MAGV) = (
			SELECT TOP 1 COUNT(GV2.MAGV) AS SLGV
			FROM GIAOVIEN AS GV2
			LEFT JOIN BOMON AS BM2
			ON GV2.MABM = BM2.MABM
			LEFT JOIN KHOA AS K2
			ON BM2.MAKHOA = K2.MAKHOA
			WHERE K2.TENKHOA = N'Công nghệ thông tin'
			GROUP BY BM2.MABM, BM2.TENBM
			ORDER BY COUNT(GV2.MAGV) DESC
		)
	)
) AND K1.TENKHOA = N'Công nghệ thông tin'
AND TG1.STT IN (
	SELECT DISTINCT COUNT(DISTINCT TG4.STT)
	FROM DETAI AS DT4
	RIGHT JOIN THAMGIADT AS TG4
	ON DT4.MADT = TG4.MADT
	WHERE DT4.GVCNDT = ANY (
		SELECT GV4.MAGV
		FROM BOMON AS BM3
		LEFT JOIN KHOA AS K3
		ON BM3.MAKHOA = K3.MAKHOA
		RIGHT JOIN GIAOVIEN AS GV3
		ON GV3.MABM = BM3.MABM
		LEFT JOIN GIAOVIEN AS GV4
		ON BM3.TRUONGBM = GV4.MAGV
		WHERE K3.TENKHOA = N'Công nghệ thông tin'
		GROUP BY BM3.MABM, GV4.MAGV
		HAVING COUNT(GV3.MAGV) = (
			SELECT TOP 1 COUNT(GV2.MAGV) AS SLGV
			FROM GIAOVIEN AS GV2
			LEFT JOIN BOMON AS BM2
			ON GV2.MABM = BM2.MABM
			LEFT JOIN KHOA AS K2
			ON BM2.MAKHOA = K2.MAKHOA
			WHERE K2.TENKHOA = N'Công nghệ thông tin'
			GROUP BY BM2.MABM, BM2.TENBM
			ORDER BY COUNT(GV2.MAGV) DESC
		)
	)
	GROUP BY TG4.MADT
)
GROUP BY TG1.MADT, TG1.STT, GV1.HOTEN
HAVING COUNT (DISTINCT TG1.STT) = (
	SELECT COUNT (DISTINCT TG4.STT)
	FROM DETAI AS DT4
	RIGHT JOIN THAMGIADT AS TG4
	ON DT4.MADT = TG4.MADT
	WHERE DT4.GVCNDT = ANY (
		SELECT GV4.MAGV
		FROM BOMON AS BM3
		LEFT JOIN KHOA AS K3
		ON BM3.MAKHOA = K3.MAKHOA
		RIGHT JOIN GIAOVIEN AS GV3
		ON GV3.MABM = BM3.MABM
		LEFT JOIN GIAOVIEN AS GV4
		ON BM3.TRUONGBM = GV4.MAGV
		WHERE K3.TENKHOA = N'Công nghệ thông tin'
		GROUP BY BM3.MABM, GV4.MAGV
		HAVING COUNT(GV3.MAGV) = (
			SELECT TOP 1 COUNT(GV2.MAGV) AS SLGV
			FROM GIAOVIEN AS GV2
			LEFT JOIN BOMON AS BM2
			ON GV2.MABM = BM2.MABM
			LEFT JOIN KHOA AS K2
			ON BM2.MAKHOA = K2.MAKHOA
			WHERE K2.TENKHOA = N'Công nghệ thông tin'
			GROUP BY BM2.MABM, BM2.TENBM
			ORDER BY COUNT(GV2.MAGV) DESC
		)
	)
)