USE QLGV
GO

--Q75--
SELECT GIAOVIEN.HOTEN, BOMON.TENBM
FROM GIAOVIEN
LEFT JOIN BOMON
ON GIAOVIEN.MAGV = BOMON.TRUONGBM

--Q76--
SELECT BOMON.TENBM, GIAOVIEN.HOTEN
FROM BOMON
LEFT JOIN GIAOVIEN
ON BOMON.TRUONGBM = GIAOVIEN.MAGV

--Q77--
SELECT GIAOVIEN.HOTEN, DETAI.TENDT
FROM GIAOVIEN
LEFT JOIN DETAI
ON GIAOVIEN.MAGV = DETAI.GVCNDT

--Q78--
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN,
(
	CASE
	WHEN GIAOVIEN.LUONG < 1800 THEN N'Thấp'
	WHEN GIAOVIEN.LUONG >= 1800 AND GIAOVIEN.LUONG <= 2000 THEN N'Trung bình'
	WHEN GIAOVIEN.LUONG > 2000 THEN 'Cao'
	END
) AS MUCLUONG
FROM GIAOVIEN

--Q79--
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, ROW_NUMBER() OVER(ORDER BY GIAOVIEN.LUONG DESC) AS XEPHANG
FROM GIAOVIEN

--Q80--
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN,
(
	CASE
	WHEN BOMON.TRUONGBM = GIAOVIEN.MAGV AND GIAOVIEN.MAGV != KHOA.TRUONGKHOA THEN GIAOVIEN.LUONG + 300
	WHEN KHOA.TRUONGKHOA = GIAOVIEN.MAGV THEN GIAOVIEN.LUONG + 600
	ELSE LUONG
	END
) AS LUONG
FROM GIAOVIEN
LEFT JOIN BOMON
ON GIAOVIEN.MAGV = BOMON.TRUONGBM
LEFT JOIN KHOA
ON BOMON.MAKHOA = KHOA.MAKHOA

--Q81--
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN,
(
	CASE
	WHEN GIAOVIEN.PHAI = 'Nam' THEN DATEADD(YEAR, 60, GIAOVIEN.NGSINH)
	WHEN GIAOVIEN.PHAI = N'Nữ' THEN DATEADD(YEAR, 55, GIAOVIEN.NGSINH)
	END
) DUKIENNGHIHUU
FROM GIAOVIEN


