USE QLGV

-- Change Data type for column PHAI in GAIOVIEN table (old data type is char (3))
ALTER TABLE GIAOVIEN
ALTER COLUMN PHAI nchar(3)

-- Update values "Nữ" for this column where values = "N?"
UPDATE GIAOVIEN
SET PHAI = N'Nữ'
WHERE PHAI = 'N?'

--Q1--
SELECT HOTEN, LUONG 
FROM GIAOVIEN
WHERE PHAI = N'Nữ'

--Q2--
SELECT HOTEN, LUONG * 1.1 AS LUONG_SAU
FROM GIAOVIEN

--Q3--
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN
FROM GIAOVIEN LEFT JOIN BOMON
ON GIAOVIEN.MAGV = BOMON.TRUONGBM
WHERE BOMON.NGAYNHANCHUC > '1995' OR (GIAOVIEN.HOTEN LIKE N'Nguyễn%' AND GIAOVIEN.LUONG > 2000)

--Q4--
SELECT GIAOVIEN.HOTEN
FROM 
GIAOVIEN LEFT JOIN BOMON
ON GIAOVIEN.MABM = BOMON.MABM
LEFT JOIN KHOA
ON BOMON.MAKHOA = KHOA.MAKHOA
WHERE KHOA.TENKHOA = N'Công nghệ thông tin'

--Q5--
SELECT BOMON.MABM, BOMON.TENBM, BOMON.PHONG, BOMON.DIENTHOAI, BOMON.MAKHOA, BOMON.TRUONGBM, 
BOMON.NGAYNHANCHUC, GIAOVIEN.HOTEN, GIAOVIEN.DIACHI, GIAOVIEN.LUONG, GIAOVIEN.NGSINH, GIAOVIEN.PHAI
FROM BOMON LEFT JOIN GIAOVIEN
ON BOMON.TRUONGBM = GIAOVIEN.MAGV

--Q6--
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, GIAOVIEN.LUONG, GIAOVIEN.PHAI,
GIAOVIEN.NGSINH, GIAOVIEN.DIACHI, GIAOVIEN.GVQLCM, GIAOVIEN.MABM,
BOMON.TENBM, BOMON.PHONG, BOMON.DIENTHOAI, BOMON.TRUONGBM, BOMON.MAKHOA, BOMON.NGAYNHANCHUC
FROM GIAOVIEN JOIN BOMON
ON GIAOVIEN.MABM = BOMON.MABM

--Q7--
SELECT DETAI.TENDT, GIAOVIEN.HOTEN
FROM
DETAI JOIN GIAOVIEN
ON DETAI.GVCNDT = GIAOVIEN.MAGV

--Q8--
SELECT *
FROM KHOA LEFT JOIN GIAOVIEN
ON KHOA.TRUONGKHOA = GIAOVIEN.MAGV

--Q9--
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, THAMGIADT.MADT, THAMGIADT.STT, THAMGIADT.PHUCAP, THAMGIADT.KETQUA
FROM THAMGIADT LEFT JOIN GIAOVIEN
ON THAMGIADT.MAGV = GIAOVIEN.MAGV
LEFT JOIN BOMON
ON GIAOVIEN.MABM = BOMON.MABM
WHERE THAMGIADT.MADT = '006' AND BOMON.TENBM = 'Vi sinh'

--Q10--
SELECT DETAI.MADT, CHUDE.TENCD, GIAOVIEN.HOTEN, GIAOVIEN.NGSINH, GIAOVIEN.DIACHI
FROM DETAI LEFT JOIN CHUDE
ON DETAI.MACD = CHUDE.MACD
LEFT JOIN GIAOVIEN
ON DETAI.GVCNDT = GIAOVIEN.MAGV
WHERE DETAI.CAPQL != N'Nhà nước' --Cấp thành phố là những cấp khác cấp nhà nước--

--Q11--
SELECT GV1.HOTEN, GV2.HOTEN AS GVQLCM
FROM GIAOVIEN AS GV1 LEFT JOIN GIAOVIEN AS GV2
ON GV1.GVQLCM = GV2.MAGV

--Q12--
SELECT GV1.HOTEN, GV2.HOTEN AS GVQLCM
FROM GIAOVIEN AS GV1 LEFT JOIN GIAOVIEN AS GV2
ON GV1.GVQLCM = GV2.MAGV
WHERE GV2.HOTEN = N'Nguyễn Thanh Tùng'

--Q13--
SELECT GIAOVIEN.HOTEN
FROM BOMON LEFT JOIN GIAOVIEN
ON BOMON.TRUONGBM = GIAOVIEN.MAGV
WHERE BOMON.TENBM = N'Hệ thống thông tin'

--Q14--
SELECT DISTINCT GIAOVIEN.HOTEN AS CNDT
FROM DETAI LEFT JOIN GIAOVIEN
ON DETAI.GVCNDT = GIAOVIEN.MAGV
LEFT JOIN CHUDE
ON DETAI.MACD = CHUDE.MACD
WHERE CHUDE.TENCD = N'Quản lý giáo dục'

--Q15--
SELECT CONGVIEC.TENCV
FROM DETAI LEFT JOIN CONGVIEC
ON DETAI.MADT = CONGVIEC.MADT
WHERE DETAI.TENDT = N'HTTT quản lý các trường ĐH' AND MONTH(CONGVIEC.NGAYBD) = 3 AND YEAR(CONGVIEC.NGAYBD) = 2008

--Q16--
SELECT GV1.HOTEN, GV2.HOTEN AS GVQLCM
FROM GIAOVIEN AS GV1 LEFT JOIN GIAOVIEN AS GV2
ON GV1.GVQLCM = GV2.MAGV

--Q17--
SELECT *
FROM CONGVIEC
WHERE NGAYBD >= '01/01/2007' AND NGAYBD <= '01/08/2007' -- Định dạng là mm/dd/yyyy (đề không nói 01/08/2007 là định dạng nào nên mặc định theo sql)

--Q18--
SELECT GV1.HOTEN
FROM GIAOVIEN AS GV1 LEFT JOIN GIAOVIEN AS GV2
ON GV1.MABM = GV2.MABM
WHERE GV2.HOTEN = N'Trần Trà Hương'

-- Nếu không muốn lấy giáo viên Trần Trà Hương thì:
SELECT GV1.HOTEN
FROM GIAOVIEN AS GV1 LEFT JOIN GIAOVIEN AS GV2
ON GV1.MABM = GV2.MABM
WHERE GV2.HOTEN = N'Trần Trà Hương' AND GV1.HOTEN != N'Trần Trà Hương'

--Q19--
SELECT DISTINCT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, GIAOVIEN.LUONG, GIAOVIEN.PHAI, GIAOVIEN.NGSINH, GIAOVIEN.DIACHI, GIAOVIEN.GVQLCM, GIAOVIEN.MABM
FROM GIAOVIEN JOIN BOMON
ON GIAOVIEN.MAGV = BOMON.TRUONGBM
JOIN DETAI
ON GIAOVIEN.MAGV = DETAI.GVCNDT

--Q20--
SELECT GIAOVIEN.HOTEN
FROM GIAOVIEN JOIN BOMON
ON GIAOVIEN.MAGV = BOMON.TRUONGBM
JOIN KHOA
ON GIAOVIEN.MAGV = KHOA.TRUONGKHOA

--Q21--
SELECT DISTINCT GIAOVIEN.HOTEN
FROM GIAOVIEN JOIN BOMON
ON GIAOVIEN.MAGV = BOMON.TRUONGBM
JOIN DETAI
ON GIAOVIEN.MAGV = DETAI.GVCNDT

--Q22--
SELECT DISTINCT GIAOVIEN.MAGV
FROM GIAOVIEN JOIN DETAI
ON GIAOVIEN.MAGV = DETAI.GVCNDT
JOIN KHOA
ON GIAOVIEN.MAGV = KHOA.TRUONGKHOA

--Q23--
SELECT DISTINCT GIAOVIEN.MAGV
FROM GIAOVIEN LEFT JOIN THAMGIADT
ON GIAOVIEN.MAGV = THAMGIADT.MAGV
WHERE GIAOVIEN.MABM = 'HTTT' OR THAMGIADT.MADT = '001'

--Q24--
SELECT DISTINCT GV1.MAGV, GV1.HOTEN, GV1.LUONG, GV1.PHAI, GV1.NGSINH, GV1.DIACHI, GV1.GVQLCM, GV1.MABM
FROM GIAOVIEN AS GV1 LEFT JOIN GIAOVIEN AS GV2
ON GV1.MABM = GV2.MABM
WHERE GV2.MAGV = '002'

--Q25--
SELECT DISTINCT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, GIAOVIEN.LUONG, GIAOVIEN.PHAI, GIAOVIEN.NGSINH, GIAOVIEN.DIACHI, GIAOVIEN.GVQLCM, GIAOVIEN.MABM
FROM GIAOVIEN RIGHT JOIN BOMON
ON GIAOVIEN.MAGV = BOMON.TRUONGBM
WHERE GIAOVIEN.MAGV <> 'NULL'

--Q26--
SELECT HOTEN, LUONG 
FROM GIAOVIEN