USE QLGV
GO

--1--
SELECT TOP 1 BOMON.MABM, BOMON.TENBM, COUNT(DISTINCT GIAOVIEN.MAGV)
FROM GIAOVIEN
LEFT JOIN GV_DT
ON GIAOVIEN.MAGV = GV_DT.MAGV
LEFT JOIN BOMON
ON GIAOVIEN.MABM = BOMON.MABM
WHERE GV_DT.DIENTHOAI IS NOT NULL
GROUP BY BOMON.MABM, BOMON.TENBM
ORDER BY COUNT(DISTINCT GIAOVIEN.MAGV) DESC

--2--
SELECT GV1.HOTEN
FROM GIAOVIEN AS GV1
JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
WHERE TG1.MADT IN (
	SELECT DT2.MADT
	FROM DETAI AS DT2
	LEFT JOIN GIAOVIEN AS GV2
	ON DT2.GVCNDT = GV2.MAGV
	WHERE GV2.HOTEN = N'Trương Nam Sơn'
)
GROUP BY TG1.MADT, GV1.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = (
	SELECT COUNT(DISTINCT DT2.MADT)
	FROM DETAI AS DT2
	LEFT JOIN GIAOVIEN AS GV2
	ON DT2.GVCNDT = GV2.MAGV
	WHERE GV2.HOTEN = N'Trương Nam Sơn'
)

--3--
SELECT GV1.HOTEN
FROM GIAOVIEN AS GV1
JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
WHERE TG1.MADT IN (
	SELECT DT2.MADT
	FROM DETAI AS DT2
	WHERE DT2.KINHPHI > 80
)
GROUP BY TG1.MADT, TG1.MAGV, GV1.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = (
	SELECT COUNT(DISTINCT DT2.MADT)
	FROM DETAI AS DT2
	RIGHT JOIN THAMGIADT AS TG2
	ON TG2.MADT = DT2.MADT
	AND TG2.MAGV = TG1.MAGV
)

--4--
DROP PROCEDURE IF EXISTS spHienThi_DSGV_ThamGia_DeTai
GO

CREATE PROCEDURE spHienThi_DSGV_ThamGia_DeTai @ngaybd DATE, @ngaykt DATE
AS
BEGIN
	IF (DATEDIFF(DAY, @ngaybd, @ngaykt) > 0)
	BEGIN
		DECLARE @vtable TABLE(MADT char(3), NGAYBD DATE, NGAYKT DATE)
		INSERT INTO @vtable SELECT DETAI.MADT, DETAI.NGAYBD, DETAI.NGAYKT FROM DETAI
		DECLARE @count int
		SELECT @count = COUNT(*) FROM @vtable
		
		-- Duyet vong lap --
		DECLARE @v_madt char(3), @v_ngaybd date, @v_ngaykt date, @sum int
		SET @sum = 0
		WHILE(@count > 0)
		BEGIN
			-- Lay dong dau tien --
			SELECT TOP 1 @v_madt = vt.MADT, @v_ngaybd = vt.NGAYBD, @v_ngaykt = vt.NGAYKT
			FROM @vtable AS vt

			-- Xu ly data --
			IF(DATEDIFF(DAY, @ngaybd, @v_ngaybd) >= 0 AND DATEDIFF(DAY, @v_ngaykt, @ngaykt) >= 0)
			BEGIN
				SET @sum = @sum + 1
				-- Xuat tat ca thong tin ve de tai --
				SELECT DETAI.*, COUNT(DISTINCT GIAOVIEN.MAGV) AS SLGV
				FROM DETAI
				LEFT JOIN THAMGIADT
				ON THAMGIADT.MADT = DETAI.MADT
				LEFT JOIN GIAOVIEN
				ON GIAOVIEN.MAGV = THAMGIADT.MAGV
				WHERE DETAI.MADT = @v_madt
				AND GIAOVIEN.MAGV != DETAI.GVCNDT
				GROUP BY DETAI.MADT, DETAI.TENDT, DETAI.CAPQL, DETAI.KINHPHI, DETAI.NGAYBD, DETAI.NGAYKT, DETAI.MACD, DETAI.GVCNDT

				-- Xuat thong tin giao vien lam chu nhiem de tai nay --
				SELECT GIAOVIEN.*
				FROM GIAOVIEN
				RIGHT JOIN DETAI
				ON GIAOVIEN.MAGV = DETAI.GVCNDT
				WHERE DETAI.MADT = @v_madt

				-- Xuat danh sach cac GV tham gia de tai nay bo qua GVCNDT --
				SELECT DISTINCT GIAOVIEN.*
				FROM GIAOVIEN
				RIGHT JOIN THAMGIADT
				ON GIAOVIEN.MAGV = THAMGIADT.MAGV
				RIGHT JOIN DETAI
				ON DETAI.MADT = THAMGIADT.MADT
				WHERE DETAI.MADT = @v_madt
				AND DETAI.GVCNDT != GIAOVIEN.MAGV
			END

			-- Xoa dong du lieu trong vtable va giam count --
			SET @count = @count - 1
			DELETE @vtable WHERE MADT = @v_madt
		END
		IF(@sum != 0)
		BEGIN
			PRINT N'Số lượng đề tài thoả yêu cầu trong thời gian trên là: ' + CAST(@sum AS char(100))
		END
		ELSE
		BEGIN
			RETURN
		END
	END

	ELSE
	BEGIN
		PRINT N'Ngày bắt đầu và ngày kết thúc không hợp lệ'
	END
END
GO

EXEC spHienThi_DSGV_ThamGia_DeTai '2006-10-20', '2009-10-20'