USE QLGV
GO

-- 1 --
SELECT BM.MABM, BM.TENBM, COUNT(DISTINCT GV.MAGV) as 'SLGV co DT'
FROM BOMON BM, GIAOVIEN GV, GV_DT DT
WHERE BM.MABM = GV.MABM AND GV.MAGV = DT.MAGV
GROUP BY BM.MABM, BM.TENBM
HAVING COUNT(DISTINCT GV.MAGV) >= ALL (
	SELECT COUNT(DISTINCT GV.MAGV)
	FROM BOMON BM, GIAOVIEN GV, GV_DT DT
	WHERE BM.MABM = GV.MABM AND GV.MAGV = DT.MAGV
	GROUP BY BM.MABM, BM.TENBM
	)

-- 2 -- 
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT MADT
	FROM DETAI DT, GIAOVIEN GV1
	WHERE DT.GVCNDT = GV1.MAGV AND GV1.HOTEN = N'Trương Nam Sơn'
EXCEPT
	SELECT MADT
	FROM THAMGIADT TG
	WHERE TG.MAGV = GV.MAGV
	)

-- 3 -- 
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.MAGV IN (
	SELECT GV.MAGV
	FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
	WHERE GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT AND DT.KINHPHI > 80
	GROUP BY GV.MAGV
	HAVING COUNT(DISTINCT DT.MADT) = (
		SELECT COUNT(DISTINCT TG.MADT)
		FROM THAMGIADT TG
		WHERE GV.MAGV = TG.MAGV 
		)
	)

-- 4 --
DROP PROCEDURE IF EXISTS spHienThi_DSGV_ThamGia_DeTai
GO

CREATE PROCEDURE spHienThi_DSGV_ThamGia_DeTai
	@Tu_Ngay date, @Den_Ngay date
AS
BEGIN
	IF (@Tu_Ngay > @Den_Ngay)
	BEGIN
		RAISERROR('Tham so vao ko hop le', 16, 1);
		RETURN;
	END

	DECLARE @DS_DETAI TABLE(MADT char(10), GVCNDT char(10), NGAYBD date);
	INSERT INTO @DS_DETAI
		SELECT MADT, GVCNDT, NGAYBD
		FROM DETAI
		WHERE (@Tu_Ngay <= NGAYBD AND NGAYBD <= @Den_Ngay )
			OR (@Tu_Ngay <= NGAYKT AND NGAYKT <= @Den_Ngay )
			OR (NGAYBD <= @Tu_Ngay AND @Den_Ngay <= NGAYKT );

	DECLARE @SL_DETAI int;
	SELECT @SL_DETAI = COUNT(*) FROM @DS_DETAI;
	PRINT 'So luong de tai thoa yeu cau:' + CAST(@SL_DETAI AS CHAR(10));
	IF ( @SL_DETAI = 0 ) RETURN;

	DECLARE @i int, @MADT char(10), @GVCNDT char(10), @SL_GVTG int;
	SET @i = 1;
	WHILE ( @i <= @SL_DETAI )
	BEGIN
		SELECT '== DE TAI #  ' + CAST(@i as char(3)) + ' / ' + CAST(@SL_DETAI as char(3)) + '===============================';
		SELECT TOP 1 @MADT = MADT, @GVCNDT = GVCNDT FROM @DS_DETAI ORDER BY NGAYBD DESC;

		SET @SL_GVTG = (SELECT COUNT(DISTINCT MAGV)
			FROM THAMGIADT
			WHERE MADT = @MADT AND MAGV <> @GVCNDT)

		SELECT DT.*, @SL_GVTG as 'SLGV tham gia'
			FROM DETAI DT
			WHERE MADT = @MADT;

		SELECT GV.*
			FROM GIAOVIEN GV
			WHERE MAGV = @GVCNDT;

		IF ( @SL_GVTG > 0 )
			SELECT GV.*
			FROM GIAOVIEN GV
			WHERE GV.MAGV <> @GVCNDT AND
				GV.MAGV IN (SELECT DISTINCT TG.MAGV
							FROM THAMGIADT TG
							WHERE TG.MADT = @MADT )
			ORDER BY (YEAR(GETDATE()) - YEAR(GV.NGSINH)) DESC;

		SET @i = @i + 1;
		DELETE @DS_DETAI WHERE MADT = @MADT;
	END

END
GO

--EXEC spHienThi_DSGV_ThamGia_DeTai '2010-1-1', '2008-1-1'

-- EXEC spHienThi_DSGV_ThamGia_DeTai '2008-1-1', '2010-1-1' --
EXEC spHienThi_DSGV_ThamGia_DeTai '2006-10-20', '2009-10-20'