USE QLGV
GO

--Q59--
SELECT DISTINCT DT1.MADT, DT1.TENDT
FROM DETAI AS DT1
RIGHT JOIN THAMGIADT AS TG1
ON TG1.MADT = DT1.MADT
WHERE TG1.MAGV IN (
	SELECT GV2.MAGV
	FROM GIAOVIEN AS GV2
	WHERE GV2.MABM = 'HTTT'
)
GROUP BY DT1.MADT, DT1.TENDT
HAVING COUNT (DISTINCT TG1.MAGV) = (
	SELECT COUNT (DISTINCT GV2.MAGV)
	FROM GIAOVIEN AS GV2
	WHERE GV2.MABM = 'HTTT'
)

--Q60--
SELECT DISTINCT DT1.MADT, DT1.TENDT
FROM DETAI AS DT1
RIGHT JOIN THAMGIADT AS TG1
ON TG1.MADT = DT1.MADT
WHERE TG1.MAGV IN (
	SELECT GV2.MAGV
	FROM GIAOVIEN AS GV2
	LEFT JOIN BOMON AS BM2
	ON GV2.MABM = BM2.MABM
	WHERE BM2.TENBM = N'Hệ thống thông tin'
)
GROUP BY DT1.MADT, DT1.TENDT
HAVING COUNT (DISTINCT TG1.MAGV) = (
	SELECT COUNT(DISTINCT GV2.MAGV)
	FROM GIAOVIEN AS GV2
	LEFT JOIN BOMON AS BM2
	ON GV2.MABM = BM2.MABM
	WHERE BM2.TENBM = N'Hệ thống thông tin'
)

--Q61--
SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN AS GV1
RIGHT JOIN THAMGIADT AS TG1
ON TG1.MAGV = GV1.MAGV
WHERE TG1.MADT IN (
	SELECT DT2.MADT
	FROM DETAI AS DT2
	WHERE DT2.MACD = 'QLGD'
)
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = (
	SELECT COUNT(DISTINCT DT2.MADT)
	FROM DETAI AS DT2
	WHERE DT2.MACD = 'QLGD'
)

--Q62--
SELECT GV1.HOTEN
FROM GIAOVIEN AS GV1
RIGHT JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
WHERE TG1.MADT IN (
	SELECT DISTINCT TG2.MADT
	FROM THAMGIADT AS TG2
	LEFT JOIN GIAOVIEN AS GV2
	ON TG2.MAGV = GV2.MAGV
	WHERE GV2.HOTEN = N'Trần Trà Hương'
) AND GV1.HOTEN != N'Trần Trà Hương'
GROUP BY GV1.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = (
	SELECT COUNT(DISTINCT TG2.MADT)
	FROM THAMGIADT AS TG2
	LEFT JOIN GIAOVIEN AS GV2
	ON TG2.MAGV = GV2.MAGV
	WHERE GV2.HOTEN = N'Trần Trà Hương'
)

--Q64--
SELECT DISTINCT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN AS GV1
RIGHT JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
WHERE TG1.STT IN (
	SELECT CV2.SOTT
	FROM CONGVIEC AS CV2
	RIGHT JOIN DETAI AS DT2
	ON CV2.MADT = DT2.MADT
	WHERE DT2.MADT = '006'
) AND TG1.MADT = '006'
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT (DISTINCT TG1.STT) = (
	SELECT COUNT (DISTINCT CV2.SOTT)
	FROM CONGVIEC AS CV2
	RIGHT JOIN DETAI AS DT2
	ON CV2.MADT = DT2.MADT
	WHERE DT2.MADT = '006'
)

--Q65--
SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN AS GV1
RIGHT JOIN THAMGIADT AS TG1
ON TG1.MAGV = GV1.MAGV
WHERE TG1.MADT IN (
	SELECT DT2.MADT
	FROM DETAI AS DT2
	LEFT JOIN CHUDE AS CD2
	ON CD2.MACD = DT2.MACD
	WHERE CD2.TENCD = N'Ứng dụng công nghệ'
)
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = (
	SELECT COUNT(DISTINCT DT2.MADT)
	FROM DETAI AS DT2
	LEFT JOIN CHUDE AS CD2
	ON CD2.MACD = DT2.MACD
	WHERE CD2.TENCD = N'Ứng dụng công nghệ'
)

--Q66--
SELECT GV1.HOTEN
FROM GIAOVIEN AS GV1
RIGHT JOIN THAMGIADT AS TG1
ON TG1.MAGV = GV1.MAGV
WHERE TG1.MADT IN (
	SELECT DT2.MADT
	FROM DETAI AS DT2
	RIGHT JOIN GIAOVIEN AS GV2
	ON DT2.GVCNDT = GV2.MAGV
	WHERE GV2.HOTEN = N'Trần Trà Hương'
)
GROUP BY GV1.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = (
	SELECT COUNT(DISTINCT DT2.MADT)
	FROM DETAI AS DT2
	RIGHT JOIN GIAOVIEN AS GV2
	ON DT2.GVCNDT = GV2.MAGV
	WHERE GV2.HOTEN = N'Trần Trà Hương'
)

--Q67--
SELECT DT1.TENDT
FROM DETAI AS DT1
LEFT JOIN THAMGIADT AS TG1
ON DT1.MADT = TG1.MADT
WHERE TG1.MAGV IN (
	SELECT GV2.MAGV
	FROM GIAOVIEN AS GV2
	LEFT JOIN BOMON AS BM2
	ON GV2.MABM = BM2.MABM
	LEFT JOIN KHOA AS K2
	ON K2.MAKHOA = BM2.MAKHOA
	WHERE K2.MAKHOA = 'CNTT'
)
GROUP BY DT1.TENDT
HAVING COUNT (DISTINCT TG1.MAGV) = (
	SELECT COUNT(DISTINCT GV2.MAGV)
	FROM GIAOVIEN AS GV2
	LEFT JOIN BOMON AS BM2
	ON GV2.MABM = BM2.MABM
	LEFT JOIN KHOA AS K2
	ON K2.MAKHOA = BM2.MAKHOA
	WHERE K2.MAKHOA = 'CNTT'
)

--Q68--
SELECT DISTINCT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN AS GV1
RIGHT JOIN THAMGIADT AS TG1
ON TG1.MAGV = GV1.MAGV
WHERE TG1.STT IN (
	SELECT CV2.SOTT
	FROM CONGVIEC AS CV2
	RIGHT JOIN DETAI AS DT2
	ON DT2.MADT = CV2.MADT
	WHERE DT2.TENDT = N'Nghiên cứu tế bào gốc'
)
GROUP BY GV1.MAGV, GV1.HOTEN, TG1.MADT
HAVING COUNT(DISTINCT TG1.STT) = (
	SELECT COUNT(CV2.SOTT)
	FROM CONGVIEC AS CV2
	RIGHT JOIN DETAI AS DT2
	ON DT2.MADT = CV2.MADT
	WHERE DT2.TENDT = N'Nghiên cứu tế bào gốc'
	AND DT2.MADT = TG1.MADT
)

--69--
SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN AS GV1
RIGHT JOIN THAMGIADT AS TG1
ON GV1.MAGV = TG1.MAGV
WHERE TG1.MADT IN (
	SELECT DT2.MADT
	FROM DETAI AS DT2
	WHERE DT2.KINHPHI > 100
)
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT (DISTINCT TG1.MADT)= (
	SELECT COUNT(DISTINCT DT2.MADT)
	FROM DETAI AS DT2
	LEFT JOIN THAMGIADT AS TG2
	ON DT2.MADT = TG2.MADT
	WHERE DT2.KINHPHI > 100
)

--70--
